name: 'BigDataAT3'
version: '1.0.0'
config-version: 2
profile: 'default'   # your dbt Cloud connection profile

model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

# Declare the month files you actually have (used to build the UNION)
vars:
  airbnb_months:
    - '05_2020'
    - '06_2020'
    - '07_2020'
    - '08_2020'
    - '09_2020'
    - '10_2020'
    - '11_2020'
    - '12_2020'
    - '01_2021'
    - '02_2021'
    - '03_2021'
    - '04_2021'

models:
  BigDataAT3:
    +materialized: view
    silver:
      +schema: silver
    gold:
      +schema: gold
      # materialize facts as table, dims/views as needed
      fact_listing_monthly:
        +materialized: table

snapshots:
  +target_schema: snapshots

# You don't need seeds since you load via Airflow → Bronze.
