name: 'BigDataAT3'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  staging:
    +materialized: view
    +schema: staging

  core:
    +materialized: table
    +schema: core

  marts:
    +materialized: table
    +schema: marts

seeds:
  bronze:
    +schema: bronze

  silver_prototype:
    +schema: silver

  gold_prototype:
    +schema: gold
