name: "BigDataAT3"
version: "1.0"
config-version: 2

profile: "user"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  BigDataAT3:
    +materialized: view
    silver:
      +schema: dbt_mrahman_silver
      +materialized: view
    gold:
      +schema: dbt_mrahman_gold
      +materialized: table

tests:
  +severity: warn           # make non-critical tests non-blocking by default
  +store_failures: false