name: 'BigDataAT3'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  BigDataAT3:
    +schema: dbt_mrahman_bronze
    +quote_columns: true

    # =====================================
    # Airbnb Raw Listings (Bronze Seeds)
    # =====================================
    +column_types:
      # Apply to all 21 parts
      '*':
        listing_id: bigint
        scrape_id: bigint
        host_id: bigint
        accommodates: integer
        price: numeric
        availability_30: integer
        number_of_reviews: integer
        review_scores_rating: numeric
        review_scores_accuracy: numeric
        review_scores_cleanliness: numeric
        review_scores_checkin: numeric
        review_scores_communication: numeric
        review_scores_value: numeric
        host_name: text
        property_type: text
        room_type: text
        host_is_superhost: text
        has_availability: text
        source_file: text
        year_month: text

    # =====================================
    # Census Seeds
    # =====================================
    census_g01_nsw_lga:
      +schema: dbt_mrahman_bronze
      description: "Raw Census G01 demographic data for NSW LGAs"
    census_g02_nsw_lga:
      +schema: dbt_mrahman_bronze
      description: "Raw Census G02 socioeconomic data for NSW LGAs"

    # =====================================
    # LGA Mapping Seeds
    # =====================================
    nsw_lga_code:
      +schema: dbt_mrahman_bronze
      description: "Mapping between NSW LGA codes and names"
    nsw_lga_suburb:
      +schema: dbt_mrahman_bronze
      description: "Mapping between NSW suburbs and their corresponding LGAs"