CREATE SCHEMA IF NOT EXISTS bronze;
CREATE TABLE IF NOT EXISTS bronze."listings_raw" (
  "LISTING_ID" TEXT,
  "SCRAPE_ID" TEXT,
  "SCRAPED_DATE" TEXT,
  "HOST_ID" TEXT,
  "HOST_NAME" TEXT,
  "HOST_SINCE" TEXT,
  "HOST_IS_SUPERHOST" TEXT,
  "HOST_NEIGHBOURHOOD" TEXT,
  "LISTING_NEIGHBOURHOOD" TEXT,
  "PROPERTY_TYPE" TEXT,
  "ROOM_TYPE" TEXT,
  "ACCOMMODATES" TEXT,
  "PRICE" TEXT,
  "HAS_AVAILABILITY" TEXT,
  "AVAILABILITY_30" TEXT,
  "NUMBER_OF_REVIEWS" TEXT,
  "REVIEW_SCORES_RATING" TEXT,
  "REVIEW_SCORES_ACCURACY" TEXT,
  "REVIEW_SCORES_CLEANLINESS" TEXT,
  "REVIEW_SCORES_CHECKIN" TEXT,
  "REVIEW_SCORES_COMMUNICATION" TEXT,
  "REVIEW_SCORES_VALUE" TEXT,
  "SOURCE_FILE" TEXT,
  "YEAR_MONTH" TEXT,
  _src_file TEXT,
  _ingested_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bronze."nsw_lga_code_raw" (
  "LGA_CODE" TEXT,
  "LGA_NAME" TEXT,
  _src_file TEXT,
  _ingested_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bronze."nsw_lga_suburb_raw" (
  "LGA_NAME" TEXT,
  "SUBURB_NAME" TEXT,
  "Unnamed: 2" TEXT,
  "Unnamed: 3" TEXT,
  "Unnamed: 4" TEXT,
  "Unnamed: 5" TEXT,
  "Unnamed: 6" TEXT,
  "Unnamed: 7" TEXT,
  "Unnamed: 8" TEXT,
  "Unnamed: 9" TEXT,
  "Unnamed: 10" TEXT,
  "Unnamed: 11" TEXT,
  "Unnamed: 12" TEXT,
  "Unnamed: 13" TEXT,
  "Unnamed: 14" TEXT,
  "Unnamed: 15" TEXT,
  "Unnamed: 16" TEXT,
  "Unnamed: 17" TEXT,
  "Unnamed: 18" TEXT,
  "Unnamed: 19" TEXT,
  "Unnamed: 20" TEXT,
  "Unnamed: 21" TEXT,
  "Unnamed: 22" TEXT,
  "Unnamed: 23" TEXT,
  "Unnamed: 24" TEXT,
  "Unnamed: 25" TEXT,
  "Unnamed: 26" TEXT,
  _src_file TEXT,
  _ingested_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bronze."census_g01_raw" (
  "LGA_CODE_2016" TEXT,
  "Tot_P_M" TEXT,
  "Tot_P_F" TEXT,
  "Tot_P_P" TEXT,
  "Age_0_4_yr_M" TEXT,
  "Age_0_4_yr_F" TEXT,
  "Age_0_4_yr_P" TEXT,
  "Age_5_14_yr_M" TEXT,
  "Age_5_14_yr_F" TEXT,
  "Age_5_14_yr_P" TEXT,
  "Age_15_19_yr_M" TEXT,
  "Age_15_19_yr_F" TEXT,
  "Age_15_19_yr_P" TEXT,
  "Age_20_24_yr_M" TEXT,
  "Age_20_24_yr_F" TEXT,
  "Age_20_24_yr_P" TEXT,
  "Age_25_34_yr_M" TEXT,
  "Age_25_34_yr_F" TEXT,
  "Age_25_34_yr_P" TEXT,
  "Age_35_44_yr_M" TEXT,
  "Age_35_44_yr_F" TEXT,
  "Age_35_44_yr_P" TEXT,
  "Age_45_54_yr_M" TEXT,
  "Age_45_54_yr_F" TEXT,
  "Age_45_54_yr_P" TEXT,
  "Age_55_64_yr_M" TEXT,
  "Age_55_64_yr_F" TEXT,
  "Age_55_64_yr_P" TEXT,
  "Age_65_74_yr_M" TEXT,
  "Age_65_74_yr_F" TEXT,
  "Age_65_74_yr_P" TEXT,
  "Age_75_84_yr_M" TEXT,
  "Age_75_84_yr_F" TEXT,
  "Age_75_84_yr_P" TEXT,
  "Age_85ov_M" TEXT,
  "Age_85ov_F" TEXT,
  "Age_85ov_P" TEXT,
  "Counted_Census_Night_home_M" TEXT,
  "Counted_Census_Night_home_F" TEXT,
  "Counted_Census_Night_home_P" TEXT,
  "Count_Census_Nt_Ewhere_Aust_M" TEXT,
  "Count_Census_Nt_Ewhere_Aust_F" TEXT,
  "Count_Census_Nt_Ewhere_Aust_P" TEXT,
  "Indigenous_psns_Aboriginal_M" TEXT,
  "Indigenous_psns_Aboriginal_F" TEXT,
  "Indigenous_psns_Aboriginal_P" TEXT,
  "Indig_psns_Torres_Strait_Is_M" TEXT,
  "Indig_psns_Torres_Strait_Is_F" TEXT,
  "Indig_psns_Torres_Strait_Is_P" TEXT,
  "Indig_Bth_Abor_Torres_St_Is_M" TEXT,
  "Indig_Bth_Abor_Torres_St_Is_F" TEXT,
  "Indig_Bth_Abor_Torres_St_Is_P" TEXT,
  "Indigenous_P_Tot_M" TEXT,
  "Indigenous_P_Tot_F" TEXT,
  "Indigenous_P_Tot_P" TEXT,
  "Birthplace_Australia_M" TEXT,
  "Birthplace_Australia_F" TEXT,
  "Birthplace_Australia_P" TEXT,
  "Birthplace_Elsewhere_M" TEXT,
  "Birthplace_Elsewhere_F" TEXT,
  "Birthplace_Elsewhere_P" TEXT,
  "Lang_spoken_home_Eng_only_M" TEXT,
  "Lang_spoken_home_Eng_only_F" TEXT,
  "Lang_spoken_home_Eng_only_P" TEXT,
  "Lang_spoken_home_Oth_Lang_M" TEXT,
  "Lang_spoken_home_Oth_Lang_F" TEXT,
  "Lang_spoken_home_Oth_Lang_P" TEXT,
  "Australian_citizen_M" TEXT,
  "Australian_citizen_F" TEXT,
  "Australian_citizen_P" TEXT,
  "Age_psns_att_educ_inst_0_4_M" TEXT,
  "Age_psns_att_educ_inst_0_4_F" TEXT,
  "Age_psns_att_educ_inst_0_4_P" TEXT,
  "Age_psns_att_educ_inst_5_14_M" TEXT,
  "Age_psns_att_educ_inst_5_14_F" TEXT,
  "Age_psns_att_educ_inst_5_14_P" TEXT,
  "Age_psns_att_edu_inst_15_19_M" TEXT,
  "Age_psns_att_edu_inst_15_19_F" TEXT,
  "Age_psns_att_edu_inst_15_19_P" TEXT,
  "Age_psns_att_edu_inst_20_24_M" TEXT,
  "Age_psns_att_edu_inst_20_24_F" TEXT,
  "Age_psns_att_edu_inst_20_24_P" TEXT,
  "Age_psns_att_edu_inst_25_ov_M" TEXT,
  "Age_psns_att_edu_inst_25_ov_F" TEXT,
  "Age_psns_att_edu_inst_25_ov_P" TEXT,
  "High_yr_schl_comp_Yr_12_eq_M" TEXT,
  "High_yr_schl_comp_Yr_12_eq_F" TEXT,
  "High_yr_schl_comp_Yr_12_eq_P" TEXT,
  "High_yr_schl_comp_Yr_11_eq_M" TEXT,
  "High_yr_schl_comp_Yr_11_eq_F" TEXT,
  "High_yr_schl_comp_Yr_11_eq_P" TEXT,
  "High_yr_schl_comp_Yr_10_eq_M" TEXT,
  "High_yr_schl_comp_Yr_10_eq_F" TEXT,
  "High_yr_schl_comp_Yr_10_eq_P" TEXT,
  "High_yr_schl_comp_Yr_9_eq_M" TEXT,
  "High_yr_schl_comp_Yr_9_eq_F" TEXT,
  "High_yr_schl_comp_Yr_9_eq_P" TEXT,
  "High_yr_schl_comp_Yr_8_belw_M" TEXT,
  "High_yr_schl_comp_Yr_8_belw_F" TEXT,
  "High_yr_schl_comp_Yr_8_belw_P" TEXT,
  "High_yr_schl_comp_D_n_g_sch_M" TEXT,
  "High_yr_schl_comp_D_n_g_sch_F" TEXT,
  "High_yr_schl_comp_D_n_g_sch_P" TEXT,
  "Count_psns_occ_priv_dwgs_M" TEXT,
  "Count_psns_occ_priv_dwgs_F" TEXT,
  "Count_psns_occ_priv_dwgs_P" TEXT,
  "Count_Persons_other_dwgs_M" TEXT,
  "Count_Persons_other_dwgs_F" TEXT,
  "Count_Persons_other_dwgs_P" TEXT,
  _src_file TEXT,
  _ingested_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bronze."census_g02_raw" (
  "LGA_CODE_2016" TEXT,
  "Median_age_persons" TEXT,
  "Median_mortgage_repay_monthly" TEXT,
  "Median_tot_prsnl_inc_weekly" TEXT,
  "Median_rent_weekly" TEXT,
  "Median_tot_fam_inc_weekly" TEXT,
  "Average_num_psns_per_bedroom" TEXT,
  "Median_tot_hhd_inc_weekly" TEXT,
  "Average_household_size" TEXT,
  _src_file TEXT,
  _ingested_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bronze_listings_src ON bronze."listings_raw"(_src_file);
SELECT * FROM {{ ref('listings_raw') }}