version: 2

models:
  - name: part_1
    description: "Staging model for cleaned and deduplicated listings and census data"
    columns:
      - name: id
        description: "Primary identifier"
        tests:
          - not_null
          - unique
