version: 2

models:
  - name: listings_base
    description: "Standardized raw listings from Bronze (one row per listing snapshot)."
    tags: ["silver"]
    columns:
      - name: listing_id
        description: "Unique listing identifier."
        tests:
          - not_null
      - name: host_id
        description: "Host identifier."
        tests:
          - not_null
      - name: room_type
        description: "Room type label."
      - name: price
        description: "Nightly price (numeric)."
      - name: availability_30
        description: "Days available in next 30 days."
      - name: year_month
        description: "YYYY-MM of the snapshot (e.g., 2020-05)."
        tests:
          - not_null

  - name: listings_monthly
    description: "Monthly grain view of listings with simple metrics (one row per listing per month)."
    tags: ["silver"]
    columns:
      - name: listing_id
        tests:
          - not_null
      - name: host_id
        tests:
          - not_null
      - name: year_month
        tests:
          - not_null
      - name: is_active
        description: "Whether listing is considered active in that month."
      - name: number_of_stays
        description: "Estimated stays in the month (derived)."
      - name: estimated_revenue
        description: "Estimated revenue in the month (derived)."