version: 2

models:
  - name: part_2
    description: "Core transformation layer that cleans and types the raw listings data for further modeling."
    columns:
      - name: listing_id
        description: "Unique ID of the listing"
        tests: [not_null, unique]

      - name: host_id
        description: "ID of the host managing the listing"
        tests: [not_null]

      - name: room_type
        description: "Type of room being offered (e.g. Entire home, Private room)"
        tests: [not_null]

      - name: property_type
        description: "Type of property (e.g. Apartment, House)"
        tests: [not_null]

      - name: accommodates
        description: "Number of people the listing can accommodate"
        tests: [not_null]

      - name: price
        description: "Nightly price of the listing in AUD"
        tests: [not_null]

      - name: availability_30
        description: "Number of days available in the next 30 days"
        tests: [not_null]

      - name: number_of_reviews
        description: "Total number of reviews received by the listing"
        tests: [not_null]

      - name: review_scores_rating
        description: "Average rating score of the listing (0-100 scale)"

      - name: suburb
        description: "Standardized suburb name"

      - name: lga_name
        description: "Mapped Local Government Area name"

      - name: lga_code
        description: "ABS code for the Local Government Area"
