version: 2

seeds:
  # ================================
  # Census Seeds
  # ================================
  - name: census_g01_nsw_lga
    description: "Raw Census G01 demographic data for NSW LGAs"
    columns:
      - name: LGA_CODE_2016
        description: "Unique LGA identifier code for 2016 Census"
        tests: [not_null, unique]

  - name: census_g02_nsw_lga
    description: "Raw Census G02 socioeconomic data for NSW LGAs"
    columns:
      - name: LGA_CODE_2016
        description: "Unique LGA identifier code for 2016 Census"
        tests: [not_null, unique]

  # ================================
  # Airbnb Raw Listings (Bronze Seeds)
  # ================================
  - name: listings_raw_part_1
    description: "First partition of Airbnb raw listings data"
  - name: listings_raw_part_2
    description: "Second partition of Airbnb raw listings data"
  - name: listings_raw_part_3
    description: "Third partition of Airbnb raw listings data"
  - name: listings_raw_part_4
    description: "Fourth partition of Airbnb raw listings data"
  - name: listings_raw_part_5
    description: "Fifth partition of Airbnb raw listings data"
  - name: listings_raw_part_6
    description: "Sixth partition of Airbnb raw listings data"
  - name: listings_raw_part_7
    description: "Seventh partition of Airbnb raw listings data"
  - name: listings_raw_part_8
    description: "Eighth partition of Airbnb raw listings data"
  - name: listings_raw_part_9
    description: "Ninth partition of Airbnb raw listings data"
  - name: listings_raw_part_10
    description: "Tenth partition of Airbnb raw listings data"
  - name: listings_raw_part_11
    description: "Eleventh partition of Airbnb raw listings data"
  - name: listings_raw_part_12
    description: "Twelfth partition of Airbnb raw listings data"
  - name: listings_raw_part_13
    description: "Thirteenth partition of Airbnb raw listings data"
  - name: listings_raw_part_14
    description: "Fourteenth partition of Airbnb raw listings data"
  - name: listings_raw_part_15
    description: "Fifteenth partition of Airbnb raw listings data"
  - name: listings_raw_part_16
    description: "Sixteenth partition of Airbnb raw listings data"
  - name: listings_raw_part_17
    description: "Seventeenth partition of Airbnb raw listings data"
  - name: listings_raw_part_18
    description: "Eighteenth partition of Airbnb raw listings data"
  - name: listings_raw_part_19
    description: "Nineteenth partition of Airbnb raw listings data"
  - name: listings_raw_part_20
    description: "Twentieth partition of Airbnb raw listings data"
  - name: listings_raw_part_21
    description: "Twenty-first partition of Airbnb raw listings data"

  # ================================
  # LGA Mapping Seeds
  # ================================
  - name: nsw_lga_code
    description: "Mapping between NSW LGA codes and names"
    columns:
      - name: LGA_CODE
        description: "Unique LGA code"
        tests: [not_null, unique]
      - name: LGA_NAME
        description: "Readable LGA name"

  - name: nsw_lga_suburb
    description: "Mapping between NSW suburbs and their corresponding LGAs"
    columns:
      - name: LGA_NAME
        description: "Name of the LGA"
        tests: [not_null]
      - name: SUBURB_NAME
        description: "Name of the suburb"
        tests: [not_null]
