version: 2

sources:
  - name: bronze
    database: postgres
    schema: bronze
    tables:
<<<<<<< HEAD
      - name: m05_2020
      - name: m06_2020
      - name: m07_2020
      - name: m08_2020
      - name: m09_2020
      - name: m10_2020
      - name: m11_2020
      - name: m12_2020
      - name: m01_2021
      - name: m02_2021
      - name: m03_2021
      - name: m04_2021
=======
      # Airbnb monthly extracts
      - name: "m05_2020"
        description: "Airbnb NSW listings — May 2020."
      - name: "m06_2020"
        description: "Airbnb NSW listings — June 2020."
      - name: "m07_2020"
        description: "Airbnb NSW listings — July 2020."
      - name: "m08_2020"
        description: "Airbnb NSW listings — August 2020."
      - name: "m09_2020"
        description: "Airbnb NSW listings — September 2020."
      - name: "m10_2020"
        description: "Airbnb NSW listings — October 2020."
      - name: "m11_2020"
        description: "Airbnb NSW listings — November 2020."
      - name: "m12_2020"
        description: "Airbnb NSW listings — December 2020."
      - name: "m01_2021"
        description: "Airbnb NSW listings — January 2021."
      - name: "m02_2021"
        description: "Airbnb NSW listings — February 2021."
      - name: "m03_2021"
        description: "Airbnb NSW listings — March 2021."
      - name: "m04_2021"
        description: "Airbnb NSW listings — April 2021."

      # Census + LGA
>>>>>>> d5f4be604a6c0c62ab332a4ced06bbfe561fee9d
      - name: "2016census_g01_nsw_lga"
      - name: "2016census_g02_nsw_lga"
      - name: nsw_lga_code
      - name: nsw_lga_suburb