version: 2

sources:
  - name: bronze
    schema: bronze
    description: "Raw Airbnb and Census data loaded from GCS into Postgres via Airflow."
    tables:
      # --- Airbnb monthly raw tables (May 2020 → Apr 2021)
      - name: 05_2020
        description: "Airbnb listings data for May 2020"
      - name: 06_2020
        description: "Airbnb listings data for June 2020"
      - name: 07_2020
        description: "Airbnb listings data for July 2020"
      - name: 08_2020
        description: "Airbnb listings data for August 2020"
      - name: 09_2020
        description: "Airbnb listings data for September 2020"
      - name: 10_2020
        description: "Airbnb listings data for October 2020"
      - name: 11_2020
        description: "Airbnb listings data for November 2020"
      - name: 12_2020
        description: "Airbnb listings data for December 2020"
      - name: 01_2021
        description: "Airbnb listings data for January 2021"
      - name: 02_2021
        description: "Airbnb listings data for February 2021"
      - name: 03_2021
        description: "Airbnb listings data for March 2021"
      - name: 04_2021
        description: "Airbnb listings data for April 2021"

      # --- Census / LGA reference tables
      - name: 2016census_g01_nsw_lga
        description: "2016 Census G01 – Selected Person Characteristics by Sex (NSW LGAs)"
      - name: 2016census_g02_nsw_lga
        description: "2016 Census G02 – Selected Medians and Averages (NSW LGAs)"
      - name: nsw_lga_code
        description: "Mapping between NSW LGA codes and names"
      - name: nsw_lga_suburb
        description: "Mapping between NSW suburbs and their corresponding LGAs"