version: 2

sources:
  - name: bronze
    description: "Raw Airbnb & Census data loaded from GCS by Airflow (Bronze layer)."
    database: postgres
    schema: bronze

    tables:
      # Airbnb monthly extracts
      - name: "05_2020"
        description: "Airbnb NSW listings — May 2020."
      - name: "06_2020"
        description: "Airbnb NSW listings — June 2020."
      - name: "07_2020"
        description: "Airbnb NSW listings — July 2020."
      - name: "08_2020"
        description: "Airbnb NSW listings — August 2020."
      - name: "09_2020"
        description: "Airbnb NSW listings — September 2020."
      - name: "10_2020"
        description: "Airbnb NSW listings — October 2020."
      - name: "11_2020"
        description: "Airbnb NSW listings — November 2020."
      - name: "12_2020"
        description: "Airbnb NSW listings — December 2020."
      - name: "01_2021"
        description: "Airbnb NSW listings — January 2021."
      - name: "02_2021"
        description: "Airbnb NSW listings — February 2021."
      - name: "03_2021"
        description: "Airbnb NSW listings — March 2021."
      - name: "04_2021"
        description: "Airbnb NSW listings — April 2021."

      # Census + LGA (produced by your DAG file-name → lower-case)
      - name: "2016census_g01_nsw_lga"
        description: "2016 Census (G01) — Selected person characteristics by sex, NSW LGAs."
      - name: "2016census_g02_nsw_lga"
        description: "2016 Census (G02) — Selected medians and averages, NSW LGAs."
      - name: "nsw_lga_code"
        description: "NSW LGA codes and names."
      - name: "nsw_lga_suburb"
        description: "NSW suburbs to LGA mapping."