version: 2

sources:
  - name: bronze
    database: postgres
    schema: bronze
    tables:
      - name: m05_2020
      - name: m06_2020
      - name: m07_2020
      - name: m08_2020
      - name: m09_2020
      - name: m10_2020
      - name: m11_2020
      - name: m12_2020
      - name: m01_2021
      - name: m02_2021
      - name: m03_2021
      - name: m04_2021
      - name: "2016census_g01_nsw_lga"
      - name: "2016census_g02_nsw_lga"
      - name: nsw_lga_code
      - name: nsw_lga_suburb